import type { Metadata } from "next";
import { Lusitana, Montserrat } from "next/font/google";
import "./globals.css";
import NavLinks from "./about/nav-links/navlinks";

const montserrat = Montserrat({ subsets: ["latin"] });
export const lusitana = Lusitana({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}antialiased`}>
        {children}
        {/* <NavLinks /> */}
        <footer
          className={`${lusitana.className} py-10 flex justify-center intems-center `}
        >
          Carolina ♥ Programadora Full Stack Web
        </footer>
      </body>
    </html>
  );
}
